### ISSUE TITLE
Change ijkl to hjkl on alt mode

### ISSUE THREAD

**Issue by lllfd** [weireweire/mover#9]
Hello, thank you very much for developing this plugin, I'm very interested in it. I would like to be able to map the move key jkli to hjkl, in the keyboard shortcut settings I only found a way to change the move cursor in edit mode, there doesn't seem to be a key binding for alt mode, how do I change the cursor move key binding for alt mode?

**Comment by weireweire** [comment]
We cannot do that for now. But I'll look into it.

**Comment by weireweire** [comment]
@lllfd feature added, please have a try. Thanks for this advice!
